FROM python:3.11

WORKDIR /app

# Сначала копируем только requirements.txt и устанавливаем зависимости
COPY app-flask/requirements.txt /app/
RUN pip install -r requirements.txt

# Затем копируем все остальное
COPY app-flask /app

CMD ["python", "app.py"]
