version: '3'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    command: python /bot/main.py
    environment:
      - BOT_TOKEN=${BOT_TOKEN}

  nginx:
    image: nginx
    volumes:
      - ./web/nginx_config/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: Dockerfile.flask
    environment:
      - FLASK_RUN_HOST=0.0.0.0
    ports:
      - "3000:5000"